### PR TITLE
expose qps configuration

### PR DESCRIPTION
**Pull request by cwdsuzhou**
Fix https://github.com/virtual-kubelet/virtual-kubelet/issues/822

### CODE REVIEW

**Comment by cwdsuzhou** [comment]
ping @cpuguy83  PTAL

**Comment by cpuguy83** [comment]
This should go in https://github.com/virtual-kubelet/node-cli

**Comment by cwdsuzhou** [comment]
Thanks

**Comment by cwdsuzhou** [comment]
new PR is https://github.com/virtual-kubelet/node-cli/pull/10

**Pull request closed without merging**
