### PR TITLE
bump golang to version 1.13.4

### PR DESCRIPTION
**Pull request by ducksecops**

### CODE REVIEW

**Comment by sargun** [comment]
Do you know if k8s is tested with 1.13.4?

**Comment by sargun** [comment]
@cpuguy83 Even though this is out of date, I'm inclined to rebase this, push to 1.13.9, and pull. What do you think?

**Comment by sargun** [comment]
This also breaks updates.

**Comment by cpuguy83** [comment]
Yes we should probably bump since 1.12 is no longer supported, but we may also need to update client k8s libs.

**Comment by sargun** [comment]
@cpuguy83 v1.16?

**Comment by sargun** [comment]
Scratch that. Kubernetes is still on Go 1.12. I do not suggest we upgrade past the version they are on.

**Pull request closed without merging**
