### PR TITLE
Remove VMWare VIC Provider

### PR DESCRIPTION
**Pull request by sargun**
This PR deletes the VMWare VIC provider.

### CODE REVIEW

**Comment by corrieb** [comment]
At the most recent VK offsite, we mentioned that we planned to remove the VIC provider. This is something I've been meaning to get to as I'm aware that the combination of vendoring providers and the VIC dependencies is difficult to manage.

That said, I'm a little shocked that a PR completely removing a vendor's provider would be submitted by anyone other than the vendor themselves - and further surprised that it would then subsequently be approved. 

I'm sorry that this has dragged on and I'm happy to expedite it. As a matter of principle though, I don't think anyone other than the vendor should be responsible for the creation / removal of providers.

**Comment by corrieb** [comment]
I'm also concerned that this PR appears to remove a bunch of unrelated Azure / Microsoft dependencies. This is also likely a byproduct of the dependency management challenge.

I'd like to propose closing this PR and I'll expedite creating one from the VMware side.

**Comment by sargun** [comment]
@corrieb A lot of these dependencies are transitive dependencies of the Docker package that VIC pulled in, or that the old version of Logrus pulled in.

I'm fine closing this PR. I was just trying to be helpful.

**Comment by sargun** [comment]
The VIC provider is a major impediment to us making progress with VK, and having to maintain a fork is not in either of our best interests. 

@corrieb Is there anything you would want to do beyond copying this PR? Although, I understand you want to open the PR / make the branch, if it's a matter of cycles, I'm open to helping.

**Comment by corrieb** [comment]
@sargun Yea, the MD needs to be cleaned up - including CONTRIBUTING and AUTHORS. Other than that, probably the net of the change will be the same. I appreciate you wanting this expedited and I am happy to commit to getting a similar PR done today. However as a matter of principle I think it's important that the vendor should take responsibility for changes affecting their provider code.

**Comment by sargun** [comment]
Okay, thanks. I'll look our for a PR EODish. I verified the dependency set to not break any of the other providers on Mac OS X, and Linux. I don't know about Windows.

**Comment by corrieb** [comment]
OK I've delegated this to @sflxn as he's currently the owner in the AUTHORS file and as such, it seems proper that he should own it. He's committed to getting it done by EOD. Once we have a PR from him, we can get it approved and merged.

**Comment by sargun** [comment]
FWIW, how to pickup my branch:

```
git remote add sargun https://github.com/sargun/virtual-kubelet.git
git fetch --all
git checkout sargun/remove-vic
git checkout -b remove-vic
git rebase origin/master
# Fix any conflicts
git rebase --continue # Only need to run if you have conflicts
# Make your further changes
git add -u
git commit --amend
```

**Comment by pires** [comment]
@corrieb I'm sorry if you were negatively surprised but my review was very clear that *you* should be the ones validating whether this should be merged or not. Also, I wasn't at the offsite so I treated this as I'd treat any other provider that doesn't seem to be maintained anymore.

**Pull request closed without merging**
