### PR TITLE
fix jaeger deprecated config

### PR DESCRIPTION
**Pull request by champly**
jaeger's config `Endpoint` has been deprecated:

```go
// Options are the options to be used when initializing a Jaeger exporter.
type Options struct {
	// Endpoint is the Jaeger HTTP Thrift endpoint.
	// For example, http://localhost:14268.
	//
	// Deprecated: Use CollectorEndpoint instead.
	Endpoint string
 ...
```

so fix must specify check condition.

### CODE REVIEW

**Comment by cpuguy83** [comment]
Thanks.
In order to merge your PR you'll need to sign the CNCF CLA: https://identity.linuxfoundation.org/projects/cncf

**Comment by champly** [comment]
> Thanks.
> In order to merge your PR you'll need to sign the CNCF CLA: https://identity.linuxfoundation.org/projects/cncf

ok, i sign the CNCF CLA now.

**Comment by cpuguy83** [comment]
From the linter:

```
gobin -run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.33.0 run ./...
cmd/virtual-kubelet/internal/commands/root/tracing_register_jaeger.go:45:5: SA1019: jOpts.Endpoint is deprecated: Use CollectorEndpoint instead.  (staticcheck)
	if jOpts.Endpoint != "" && jOpts.CollectorEndpoint == "" {
	   ^
cmd/virtual-kubelet/internal/commands/root/tracing_register_jaeger.go:46:58: SA1019: jOpts.Endpoint is deprecated: Use CollectorEndpoint instead.  (staticcheck)
		jOpts.CollectorEndpoint = fmt.Sprintf("%s/api/traces", jOpts.Endpoint)
		                                                       ^
cmd/virtual-kubelet/internal/commands/root/tracing_register_jaeger.go:48:66: directive `// nolint:staticcheck` is unused for linter staticcheck (nolintlint)
	if jOpts.CollectorEndpoint == "" && jOpts.AgentEndpoint == "" { // nolint:staticcheck
	                                                                ^
make: *** [Makefile:198: lint] Error 1
```

**Comment by champly** [comment]
> From the linter:
> 
> ```
> gobin -run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.33.0 run ./...
> cmd/virtual-kubelet/internal/commands/root/tracing_register_jaeger.go:45:5: SA1019: jOpts.Endpoint is deprecated: Use CollectorEndpoint instead.  (staticcheck)
> 	if jOpts.Endpoint != "" && jOpts.CollectorEndpoint == "" {
> 	   ^
> cmd/virtual-kubelet/internal/commands/root/tracing_register_jaeger.go:46:58: SA1019: jOpts.Endpoint is deprecated: Use CollectorEndpoint instead.  (staticcheck)
> 		jOpts.CollectorEndpoint = fmt.Sprintf("%s/api/traces", jOpts.Endpoint)
> 		                                                       ^
> cmd/virtual-kubelet/internal/commands/root/tracing_register_jaeger.go:48:66: directive `// nolint:staticcheck` is unused for linter staticcheck (nolintlint)
> 	if jOpts.CollectorEndpoint == "" && jOpts.AgentEndpoint == "" { // nolint:staticcheck
> 	                                                                ^
> make: *** [Makefile:198: lint] Error 1
> ```

Fix it, PTAL

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
