### PR TITLE
Use Go modules instead of dep

### PR DESCRIPTION
**Pull request by lucperkins**
`dep` is not a bad tool, but the Go community is pretty clearly standardizing on Go modules. There may have been reasons for using `dep` that I'm unaware of. If so, feel to close and disregard this PR.

### CODE REVIEW

**Comment by cpuguy83** [comment]
This looks great.
We will need to update the Makefile to add `GO111MOUDLE ?= on` and maybe a script similar to the dep check that just runs `go mod tidy` and checks the diff.

**Comment by cpuguy83** [comment]
circleci images should also be updated to 1.11.

**Comment by cpuguy83** [comment]
I made a script thingy here: https://github.com/virtual-kubelet/azure-aci/blob/master/hack/ci/check_mods.sh

**Comment by cpuguy83** [comment]
I tried to carry this, however there's some non-trivial issues to deal with... particular when running `go mod tidy` *after* Gopkg.toml is removed.

So far I have run into issues with pulling the right version of azure-sdk-for-go, and then the dreaded "Siruspen" vs "sirupsen" iussue (#542)

**Comment by lucperkins** [comment]
@cpuguy83 Yeah, I essentially submitted the PR exploratorily, as I wasn’t sure how CI would respond. I’ll poke around a bit more and see what I can do, but this may be better left to someone closer to the project internals.

**Comment by lucperkins** [comment]
@cpuguy83 As this is a bit beyond my knowledge of the project, I'm going to leave this to others (it looks like efforts may already be underway).

**Pull request closed without merging**
