### PR TITLE
Patch/vk chart namespace

### PR DESCRIPTION
**Pull request by sabbour**
Modified the Virtual Kubelet Helm charts to accept a `monitoredNamespace` parameter. The value of the parameter by default is empty. When an empty value is passed to the virtual-kublet binary, it will default to using `corev1.NamespaceAll` which is the expected behavior according to the documentation.

A separate PR is required for az cli install-connector to accept and pass this parameter to the Helm chart command.

### CODE REVIEW

**Comment by robbiezhang** [comment]
Thanks for the PR. @sabbour, can you create a helm chart package to replace the existing one?

**Comment by sabbour** [comment]
@robbiezhang which version should I use for the chart?

**Comment by sabbour** [comment]
By the way, running the latest version gives me weird errors now on my cluster:

```
2018/06/24 08:43:23 Pod watcher event is received: MODIFIED
2018/06/24 08:43:23 Pod watcher connection is closed unexpectedly.
2018/06/24 08:43:29 Error creating pod 'nginx-deployment-55968969b8-m9wjl': api call to https://management.azure.com/subscriptions/90ab3701-83f0-4ba1-a90a-f2e68683adab/resourceGroups/MC_aks-weu_aks-weu_westeurope/providers/Microsoft.ContainerInstance/containerGroups/default-nginx-deployment-55968969b8-m9wjl?api-version=2018-02-01-preview: got HTTP response status code 400 error code "InvalidRequestContent": The request content was invalid and could not be deserialized: 'Required property 'username' not found in JSON. Path 'properties.imageRegistryCredentials[0]', line 1, position 818.'.
```

**Comment by robbiezhang** [comment]
The change looks good too me. For the error, do you have another deployment `nginx-deployment-default` in your cluster? What's the spec?

**Comment by robbiezhang** [comment]
please move the 2 new charts into the charts folder.

**Comment by sabbour** [comment]
No other nginx deployment. I did a `helm delete --purge virtual-kubelet` between tests.

**Comment by robbiezhang** [comment]
Please run `kubectl get po nginx-deployment-default-554558c8f9-x4x8b -a` to see whether the pod exists. I guess that there is something weird in the spec.

**Comment by sabbour** [comment]
```
kubectl get pod nginx-deployment-554558c8f9-78bjz -a

Flag --show-all has been deprecated, will be removed in an upcoming release
NAME                                READY     STATUS           RESTARTS   AGE
nginx-deployment-554558c8f9-78bjz   0/1       ProviderFailed   0          1m
```

This is how I provisioned the Virtual Kubelet:

```
helm install . --name "$RELEASE_NAME" \
    --set env.monitoredNamespace="default",env.azureClientId="$AZURE_CLIENT_ID",env.azureClientKey="$AZURE_CLIENT_SECRET",env.azureTenantId="$AZURE_TENANT_ID",env.azureSubscriptionId="$AZURE_SUBSCRIPTION_ID",env.aciRegion="$ACI_REGION",env.aciResourceGroup="$AZURE_RG",env.nodeName="$NODE_NAME",env.nodeOsType="Linux",env.apiserverCert=$cert,env.apiserverKey=$key,rbac.install=false
```

**Comment by sabbour** [comment]
I moved the charts up in the folder structure. @robbiezhang I would appreciate if you are able to test them and confirm whether you are seeing the same bug. I don't think it is related to the change I've done but I want to be sure.

**Comment by robbiezhang** [comment]
@sabbour I've verified the new chart, it works well, and the default namespace is set to empty (all namespaces). The issue should not be related to your change. Thanks for the contribution!

I'll make a change in the `az aks install-connector` to switch to the new version. For now, we can use `--chart-url https://github.com/sabbour/virtual-kubelet/raw/master/charts/virtual-kubelet-for-aks-0.1.4.tgz` to override the default helm chart.

**Pull request merged**
