### PR TITLE
Don't skip pods status update if provider failed once but recovered with retry

### LINKED ISSUE #399: Failed pods not reconciled
When a pod fails we set the reason "ProviderFailed" but the pod state still says "Pending".
This state never gets reconciled and a pod deployment will be short until the pod is either deleted by the user or it's state updated to Failed.

### PR DESCRIPTION
**Pull request by turkenh**
More context [here](https://github.com/virtual-kubelet/virtual-kubelet/issues/399#issuecomment-704186791).

Closes #399

Signed-off-by: Hasan Turken <turkenh@gmail.com>

### CODE REVIEW

**Comment by cpuguy83** [comment]
This seems mostly there because it was already there.
I think this is fine.

I'd argue we should never skip a pod status update... however we have the case where we ping the backend every 5 seconds and send a pod status update.... maybe we could move this function call to only run in that case.

**Review by sargun — APPROVED** [review]

**Comment by sargun** [comment]
Sweet.

**Comment by sargun** [comment]
AFAICT, this should only come up in the sync case really -- or if it happens at VK startup time, because async notifications should never get this set.

**Comment by sargun** [comment]
@cpuguy83 ^

**Comment by cpuguy83** [comment]
@turkenh Looks like you need to sign the CNCF CLA?

**Comment by turkenh** [comment]
> @turkenh Looks like you need to sign the CNCF CLA?

@cpuguy83 now it is fixed, thanks.

**Comment by sargun** [comment]
Thanks for signing the CNCF CLA.

**Pull request merged**
