### PR TITLE
Remove k8s.io/kubernetes dep from env.go

### PR DESCRIPTION
**Pull request by miekg**
Put 3 k8s.io/kubernetes packages in internal/kubernetes to prevent
depending on k8s.io/kubernetes

See: #940

Probably depends on the merge of #945

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

**Comment by sargun** [comment]
Can we automate this in any fashion? I know the Kubernetes project itself has some "magic" to do this. In other projects, I've written a mini-tool to do this (example: https://github.com/Netflix/titus-executor/blob/master/fix/main.go)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [virtual-kubelet/virtual-kubele..." ]
>Can we automate this in any fashion? I know the Kubernetes project itself has
>some "magic" to do this. In other projects, I've written a mini-tool to do this
>(example: https://github.com/Netflix/titus-executor/blob/master/fix/main.go)

Nice - this hadn't crossed my mind. Probably worth adding a comment in each file which
upstream hash we've copied and (maybe?) the exact upstream directory?

(and copying the actual files, etc, etc)

/Miek

--
Miek Gieben

**Comment by sargun** [comment]
Yeah, that's a good idea, but I have no idea how to do that.

**Comment by sargun** [comment]
Any luck investigating automation?

**Comment by cpuguy83** [comment]
@sargun I think the best bet long term is to make a new module separate from k/k and get k/k to use it.
Parsing k8s yaml seems like a really useful thing outside of the kubelet codebase.

**Pull request closed without merging**
