### PR TITLE
Add the ability to configure klog from VK

### PR DESCRIPTION
**Pull request by sargun**
All of Kubernetes logging is based on klog. Klog currently does
not output any logging information to logrus, so you're flying
somewhat blind to Kubernetes internals.

This exposes the full set of configurables that klog offers,
but decorates (prefixes) the klog configuration with "klog".

The help output looks something like this:

```
      --disable-taint                         disable the virtual-kubelet node taint
      --enable-node-lease                     use node leases (1.13) for node heartbeats
      --full-resync-period duration           how often to perform a full resync of pods between kubernetes and the provider (default 1m0s)
  -h, --help                                  help for virtual-kubelet
      --klog.alsologtostderr                  log to standard error as well as files
      --klog.log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --klog.log_dir string                   If non-empty, write log files in this directory
      --klog.log_file string                  If non-empty, use this log file
      --klog.logtostderr                      log to standard error instead of files
      --klog.skip_headers                     If true, avoid header prefixes in the log messages
      --klog.stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --klog.v Level                          log level for V logs
      --klog.vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
      --kubeconfig string                     kube config file to use for connecting to the Kubernetes API server (default "/Users/sargun/.kube/config")
      --log-level string                      set the log level, e.g. "debug", "info", "warn", "error" (default "info")
      --metrics-addr string                   address to listen for metrics/stats requests (default ":10255")
      --namespace string                      kubernetes namespace (default is 'all')
      --nodename string                       kubernetes node name (default "virtual-kubelet")
      --os string                             Operating System (Linux/Windows) (default "Linux")
      --pod-sync-workers int                  set the number of pod synchronization workers (default 10)
      --provider string                       cloud provider
      --provider-config string                cloud provider configuration file
      --trace-exporter strings                sets the tracing exporter to use, available exporters: [jaeger ocagent]
      --trace-sample-rate string              set probability of tracing samples
      --trace-service-name string             sets the name of the service used to register with the trace exporter (default "virtual-kubelet")
      --trace-tag map                         add tags to include with traces in key=value form
```

### CODE REVIEW

**Comment by sargun** [comment]
All kubernetes logs are in klog, and although this doesn't allow you to pipe klog out the VK logger, it makes debugging much easier.

**Comment by cpuguy83** [comment]
So, I don't really care what logger we use.
I think at the time when we chose to standardize on logrus klog wasn't quite a thing yet, and I completely detest glog.

I'm not a huge fan of klog either (the various levels of verbosity makes things weird to work with)... but again if we can make it easy to use and decorate, I'm fine.

If we need to make changes to the logging interface to more easily support klog for projects that want to use vk as a lib, definitely +1 to that.
The current interface mostly just matches what we were already using.

I'm not quite sure what this PR does outside of adding flags, though. Do you get additional output after configuring the klog flags?

**Comment by sargun** [comment]
Yeah, so, for example, you can get raw K8s logs like this:

```
nfml-sdhillon37G:virtual-kubelet sargun$ go build -tags=mock_provider ./cmd/virtual-kubelet/ && ./virtual-kubelet --provider-config poop.json --provider mock --startup-timeout 10s --klog.v=10 --klog.logtostderr
I0506 09:49:29.033528   27267 loader.go:359] Config loaded from file /Users/sargun/.kube/config
I0506 09:49:29.034303   27267 reflector.go:131] Starting reflector *v1.Secret (1m0s) from k8s.io/client-go/informers/factory.go:132
I0506 09:49:29.034303   27267 reflector.go:131] Starting reflector *v1.ConfigMap (1m0s) from k8s.io/client-go/informers/factory.go:132
I0506 09:49:29.034432   27267 reflector.go:169] Listing and watching *v1.ConfigMap from k8s.io/client-go/informers/factory.go:132
I0506 09:49:29.034421   27267 reflector.go:169] Listing and watching *v1.Secret from k8s.io/client-go/informers/factory.go:132
ERRO[0000] TLS certificates not provided, not setting up pod http server  certPath= keyPath= node=virtual-kubelet operatingSystem=Linux provider=mock watchedNamespace=
I0506 09:49:29.034396   27267 reflector.go:131] Starting reflector *v1.Pod (1m0s) from k8s.io/client-go/informers/factory.go:132
I0506 09:49:29.034510   27267 reflector.go:169] Listing and watching *v1.Pod from k8s.io/client-go/informers/factory.go:132
I0506 09:49:29.034763   27267 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: virtual-kubelet/v0.0.0 (darwin/amd64) kubernetes/$Format" 'http://192.168.112.128:1234/api/v1/secrets?limit=500&resourceVersion=0'
I0506 09:49:29.034766   27267 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: virtual-kubelet/v0.0.0 (darwin/amd64) kubernetes/$Format" 'http://192.168.112.128:1234/api/v1/configmaps?limit=500&resourceVersion=0'
I0506 09:49:29.034763   27267 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: virtual-kubelet/v0.0.0 (darwin/amd64) kubernetes/$Format" 'http://192.168.112.128:1234/api/v1/pods?fieldSelector=spec.nodeName%3Dvirtual-kubelet&limit=500&resourceVersion=0'
INFO[0000] Waiting for pod controller / VK to be ready   node=virtual-kubelet operatingSystem=Linux provider=mock watchedNamespace=
I0506 09:49:29.037086   27267 round_trippers.go:438] GET http://192.168.112.128:1234/api/v1/configmaps?limit=500&resourceVersion=0 200 OK in 2 milliseconds
I0506 09:49:29.037097   27267 round_trippers.go:444] Response Headers:
I0506 09:49:29.037103   27267 round_trippers.go:447]     Content-Length: 408
I0506 09:49:29.037107   27267 round_trippers.go:447]     Content-Type: application/json
I0506 09:49:29.037111   27267 round_trippers.go:447]     Date: Fri, 03 May 2019 08:30:20 GMT
I0506 09:49:29.037123   27267 round_trippers.go:438] GET http://192.168.112.128:1234/api/v1/secrets?limit=500&resourceVersion=0 200 OK in 2 milliseconds
I0506 09:49:29.037132   27267 round_trippers.go:444] Response Headers:
I0506 09:49:29.037137   27267 round_trippers.go:447]     Date: Fri, 03 May 2019 08:30:20 GMT
I0506 09:49:29.037142   27267 round_trippers.go:447]     Content-Length: 117
I0506 09:49:29.037147   27267 round_trippers.go:447]     Content-Type: application/json
I0506 09:49:29.037160   27267 request.go:942] Response Body: {"kind":"ConfigMapList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/configmaps","resourceVersion":"471"},"items":[{"metadata":{"name":"extension-apiserver-authentication","namespace":"kube-system","selfLink":"/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication","uid":"427773c8-6d78-11e9-8939-000c29a24b34","resourceVersion":"38","creationTimestamp":"2019-05-03T07:51:29Z"}}]}
I0506 09:49:29.037185   27267 request.go:942] Response Body: {"kind":"SecretList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/secrets","resourceVersion":"471"},"items":[]}
I0506 09:49:29.037458   27267 round_trippers.go:438] GET http://192.168.112.128:1234/api/v1/pods?fieldSelector=spec.nodeName%3Dvirtual-kubelet&limit=500&resourceVersion=0 200 OK in 2 milliseconds
I0506 09:49:29.037468   27267 round_trippers.go:444] Response Headers:
I0506 09:49:29.037473   27267 round_trippers.go:447]     Content-Length: 111
I0506 09:49:29.037477   27267 round_trippers.go:447]     Content-Type: application/json
I0506 09:49:29.037481   27267 round_trippers.go:447]     Date: Fri, 03 May 2019 08:30:20 GMT
I0506 09:49:29.037526   27267 request.go:942] Response Body: {"kind":"PodList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/pods","resourceVersion":"474"},"items":[]}
I0506 09:49:29.038585   27267 round_trippers.go:419] curl -k -v -XGET  -H "User-Agent: virtual-kubelet/v0.0.0 (darwin/amd64) kubernetes/$Format" -H "Accept: application/json, */*" 'http://192.168.112.128:1234/api/v1/secrets?resourceVersion=471&timeout=8m1s&timeoutSeconds=481&watch=true'
I0506 09:49:29.038722   27267 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: virtual-kubelet/v0.0.0 (darwin/amd64) kubernetes/$Format" 'http://192.168.112.128:1234/api/v1/configmaps?resourceVersion=471&timeout=9m42s&timeoutSeconds=582&watch=true'
```

It's super useful for troubleshooting weird Apiserver <-> vkubelet communication issues.

**Comment by sargun** [comment]
I personally don't think we should use klog for anything, but it's what Kubenetes uses, and I don't know if there is a good way for us to fork it into logrus

**Comment by cpuguy83** [comment]
Aha! I see, these logs are coming from the k8s libs, then?

**Comment by sargun** [comment]
Yep. All of the internal kubernetes stuff uses klog.

**Comment by cpuguy83** [comment]
Cool, I'm fine with this.
Can you resolve the conflict?

**Comment by sargun** [comment]
Done

**Comment by cpuguy83** [comment]
@pires LGTY?

**Pull request merged**
