### PR TITLE
fix lint warnings

### PR DESCRIPTION
**Pull request by toshi0607**
fix lint warnings reported by
* gofmt
* misspell

### CODE REVIEW

**Comment by sargun** [comment]
What version of Go did you do this with?

**Comment by toshi0607** [comment]
@sargun  I tried with 1.11.4, 1.12.5, 1.13. And [Go Report Card](https://goreportcard.com/report/github.com/virtual-kubelet/virtual-kubelet) reports this!

**Comment by sargun** [comment]
Any reason why golint didn't catch this?

**Comment by toshi0607** [comment]
This is not a result from `golint` or `goimports` specified in `.golangci.yml`, but `gofmt -s`.

**Pull request merged**
