### PR TITLE
Fix non-linked reference to Providers in Usage

### PR DESCRIPTION
**Pull request by TBBle**
Fixes a typo ("provides") and also replaces "listed above" with a link to the list. Which had moved below, as it happens.

### CODE REVIEW

**Comment by TBBle** [comment]
Chasing up corporate CLA signature on my end.

**Comment by cpuguy83** [comment]
Any news here?

**Comment by TBBle** [comment]
Not yet. I'll chase up on Monday.

**Comment by TBBle** [comment]
I signed it

**Comment by cpuguy83** [comment]
CLA check still doesn't like it. :(
Do you have the email you signed with listed in your GH account?

**Comment by TBBle** [comment]
Yup. [The commit](https://github.com/virtual-kubelet/virtual-kubelet/commit/57cf5f75445965fd727f4d5f77ac5821fcf91002.patch) shows
```
From: "Paul \"TBBle\" Hampson" <p_hampson@wargaming.net>
```
and the rest looks right:
image
and
image

I'm not sure if I'm missing a step, or if I need to punt this back up to someone in my company. -_-

**Comment by TBBle** [comment]
/assign @TBBle
So I can find this again when the CLA is signed.

**Comment by TBBle** [comment]
I signed it.

**Comment by TBBle** [comment]
Gah, still not working, I guess. Back to emailing people about CLAs. I wish the CLA check had some kind of log to tell me which step is failing.

**Comment by TBBle** [comment]
I signed it

**Comment by TBBle** [comment]
@cpuguy83 Is there any chance you can see what's happening with the CLA bot? I've confirmed on https://corporate.lfcla.com/ that both my email address (p_hampson@wargaming.net) and my GitHub username are listed for the CNCF CLA for my company (Wargaming Group Limited).

**Comment by cpuguy83** [comment]
Do you have your corp email linked to your GH account?

For instance, here the emails I have in my GH settings:

image

**Comment by TBBle** [comment]
Yup, they're still there.
image

**Comment by TBBle** [comment]
I've raised a [support ticket](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-2351) to try and get the CLA issue resolved.

**Comment by TBBle** [comment]
I signed it

**Comment by cpuguy83** [comment]
:( Still doesn't like that sig.

**Comment by TBBle** [comment]
Yeah. We're working through with support, basically had to restart the CLA process from scratch between LF has _two_ CLA systems, and we did our CLA in the (newer) system that supports _everything except Kubernetes_.

**Comment by TBBle** [comment]
I signed it.

I need to rebase, but I signed it.

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
