### PR TITLE
Fnuarnav/virtual kubelet metrics update proposal

### PR DESCRIPTION
**Pull request by fnuarnav**
Added Proposal for Virtual Kubelet Metrics Update
 google doc here: https://docs.google.com/document/d/1GSTR8YJZE6ltVML4Gr1FqZeajUPTJswTFk0D6sCq0gI/edit

### CODE REVIEW

**Comment by cpuguy83** [comment]
Thanks for writing this up.
The proposed solution SGTM.

@helayoty

**Review by pires — COMMENTED** [review]
I'd prefer for the code to be embedded as Markdown instead of images. Is this something you can do? 🙏🏻

**Comment by fnuarnav** [comment]
> I'd prefer for the code to be embedded as Markdown instead of images. Is this something you can do? 🙏🏻

removed images and embedded code in the markdown

**Review by pires — APPROVED** [review]
LGTM

**Pull request merged**
