### PR TITLE
security update for websocket

### PR DESCRIPTION
**Pull request by jguice**
Updated the minimal dependencies (AFAICT) to ensure _only_ `websocket > 1.4.0` appeared in `go mod graph`.

Ran `make test` to verify.

See https://github.com/advisories/GHSA-3xh2-74w9-5vxm for details on the security issue.

### CODE REVIEW

**Comment by jguice** [comment]
Hi, can someone approve running the workflow for this one?

**Comment by jguice** [comment]
Thanks @cpuguy83 🙂.  When should we expect to see the results of these checks?

image

**Comment by cpuguy83** [comment]
Maybe try force pushing over the commit? (e.g. "git commit --amend --no-edit", then "git push - f")

**Comment by jguice** [comment]
@cpuguy83 looks like it's back to requiring maintainer approval to run the workflows after the forced push.

**Comment by cpuguy83** [comment]
We've resolved the CI issues. Looks like some conflicts in go.mod need to be resolved for this PR, though.

**Comment by helayoty** [comment]
@jguice  would you please rebase the PR so we can merge it?

**Comment by pires** [comment]
It is unfortunate we were not able to merge this on time. Meanwhile, other changes addressed the issue and this PR is no longer needed. I'm very sorry, @jguice. Thank you so much for your contribution.

**Comment by pires** [comment]
The fix landed in https://github.com/virtual-kubelet/virtual-kubelet/commit/70848cfdaee850fd33a360f3761fdef3d9a3d04a

**Pull request closed without merging**
