### PR TITLE
providers: remove hypersh provider

### PR DESCRIPTION
**Pull request by pires**
Hyper.sh was [shutdown](https://blog.hyper.sh/close_hyper_sh.html) on Jan 16, 2019. Hence, there's no reason to keep the `hypersh` provider around. This also allows us to prune `vendor/` significantly.

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @Jimmy-Xu just to confirm.

Thanks!

**Comment by lucperkins** [comment]
Make sure to also remove it from the website: https://github.com/virtual-kubelet/virtual-kubelet/blob/master/website/data/providers.yaml

**Comment by pires** [comment]
@lucperkins [it already was](https://github.com/virtual-kubelet/virtual-kubelet/pull/524/files#diff-184598709d96629d48393d342daeca35L13).

**Comment by pires** [comment]
Fixed conflicts and force-pushed.

**Comment by lucperkins** [comment]
@pires Ah, excellent

**Comment by rbitia** [comment]
Alright let's merge this.

**Pull request merged**
