### PR TITLE
Import kubernetes/remotecommand

### PR DESCRIPTION
**Pull request by miekg**
Copy/paste some more kubernetes code. This is to remove the dep on
kubernetes/kubernetes from within exec.go

See #940

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

**Comment by miekg** [comment]
LOL linter complains
~~~
/bin/bash: kubectl: command not found
GO111MODULE=off go get -u github.com/myitcv/gobin
gobin -run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.33.0 run ./...
internal/kubernetes/remotecommand/exec.go:56:19: Error return value of `ctx.writeStatus` is not checked (errcheck)
			ctx.writeStatus(&apierrors.StatusError{ErrStatus: metav1.Status{
			               ^
internal/kubernetes/remotecommand/exec.go:72:19: Error return value of `ctx.writeStatus` is not checked (errcheck)
			ctx.writeStatus(apierrors.NewInternalError(err))
			               ^
internal/kubernetes/remotecommand/exec.go:75:18: Error return value of `ctx.writeStatus` is not checked (errcheck)
		ctx.writeStatus(&apierrors.StatusError{ErrStatus: metav1.Status{
		               ^
internal/kubernetes/remotecommand/httpstream.go:375:23: Error return value of `stream.Reset` is not checked (errcheck)
				defer stream.Reset()
				                  ^
internal/kubernetes/remotecommand/websocket.go:108:31: Error return value of `(io.Writer).Write` is not checked (errcheck)
		streams[stdoutChannel].Write([]byte{})
		                            ^
internal/kubernetes/remotecommand/websocket.go:110:31: Error return value of `(io.Writer).Write` is not checked (errcheck)
		streams[stderrChannel].Write([]byte{})
		                            ^
internal/kubernetes/remotecommand/websocket.go:112:30: Error return value of `(io.Writer).Write` is not checked (errcheck)
		streams[errorChannel].Write([]byte{})
		                           ^
make: *** [Makefile:198: lint] Error 1
~~~

**Comment by miekg** [comment]
what should I do here? Add //golint:no everywhere? That would complicate future updates (i.e. no copy/paste anymore) or can we exclude the entire directory from golint?

**Comment by Kent-H** [comment]
@miekg You should be able to add a skip-dirs or skip-files section to .golangci.yml (https://golangci-lint.run/usage/configuration/)

(This is a good change.  The `replace` hack breaks my IDE.)

**Review by cpuguy83 — APPROVED** [review]
LGTM

**Pull request merged**
