### PR TITLE
Support building an allow-list of providers

### PR DESCRIPTION
**Pull request by cpuguy83**
Flip the boolean for provider build tags.

Also adds a sub-command to check which providers are compiled in.

### CODE REVIEW

**Comment by cpuguy83** [comment]
I hadn't really thought to just switch these around. In this case we can just do the opposite and have a default `make build` include all providers except those in an exclude list.

The main reason I did the negation build tags was just to get something in to be able to configure it without breaking people and spending a bunch of time on it.
I think this could be flipped around easily enough. The main thing is I didn't want to break the default case of just a plain `make build`.
Does that change (using `aws_provider` instead of `no_aws_provider`) work for you if we still default to building all providers, at least for now?

**Comment by pires** [comment]
But of course. That's why I gave my _approval_ in the first place ;)

**Comment by cpuguy83** [comment]
@pires OK, updated this to flip around those tags. PTAL.

**Comment by cpuguy83** [comment]
Fixed conflicts, all green. Merging. 🎉 🌮

**Pull request merged**
