### PR TITLE
Use I/O stream for provider logs interface

### PR DESCRIPTION
**Pull request by cpuguy83**
Providers must still update the implementation to actually gain any
benefit here, but this makes the provider interface a bit more sane.

### CODE REVIEW

**Comment by cpuguy83** [comment]
The only provider I've really changed is aws... which I was considering just dropping back to minimal changes.

**Comment by pires** [comment]
Yes, please do.

**Comment by cpuguy83** [comment]
Updated.

**Comment by pires** [comment]
@cpuguy83 please fix the conflict and let's have this merged.

**Pull request merged**
