### PR TITLE
Upgrade to golangci-lint v1.32.2

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Review by cpuguy83 — APPROVED** [review]
LGTM

I'm still not sure I like this error handling, but it's way better.

**Comment by cpuguy83** [comment]
You do have an extra change that's not golint, can you split that?

**Comment by sargun** [comment]
@cpuguy83 that extra change was an issue detected by golang lint. Previously, we were ignoring the error.

**Comment by sargun** [comment]
@cpuguy83 I split it into two commits.

**Pull request merged**
