### PR TITLE
Remove sfmesh provider

### PR DESCRIPTION
**Pull request by cpuguy83**
This is not being supported and as such it was requested (internally) to
be removed.

### CODE REVIEW

**Comment by cpuguy83** [comment]
ping @dkkapur @rbitia

**Comment by cpuguy83** [comment]
Ah, I was looking for where that list is...

**Comment by rbitia** [comment]
And one more thing, @lucperkins has it a list on the website

**Comment by cpuguy83** [comment]
Should be all good here.

**Pull request merged**
