### PR TITLE
VMware vSphere Integrated Containers provider

### PR DESCRIPTION
**Pull request by sflxn**
Initial PR submission for the VMware's VIC provider.

### CODE REVIEW

**Comment by sflxn** [comment]
I'm going to redo the PR to try and prune out unused vendor files.

**Comment by rbitia** [comment]
Testing right now and just pushed a test image to rbitia/vk:vic

**Comment by rbitia** [comment]
Rias-MacBook-Pro:demos riabhatia$ kubectl logs connectorvic-virtual-kubelet-for-aks-6886d6b679-dbj8k
time="2018-06-01T19:40:38Z" level=error msg="interface public not found"
/.kube/config
2018/06/01 19:40:38 Reading ACS credential file "/etc/acs/azure.json"
2018/06/01 19:40:38 Load ACS credential file "/etc/acs/azure.json" successfully
2018/06/01 19:40:38 Node 'testingaciconnector' with OS type 'Linux' registered
2018/06/01 19:40:38 tls: failed to find any PEM data in certificate input
Rias-MacBook-Pro:demos riabhatia$ kubectl get pods
NAME                                                            READY     STATUS        RESTARTS   AGE
connector-virtual-kubelet-for-aks-5444b4b56d-266bt              1/1       Running       1          52m
connectorvic-virtual-kubelet-for-aks-6886d6b679-dbj8k           1/1       Running       0          3m
myaciconnector-linux-virtual-kubelet-for-aks-56867b46bd-m59s5   1/1       Running       312        9d
nginx                                                           1/1       Terminating   0          9d
testnginx                                                       1/1       Running       0          49m

I don't see the extra node yet... Not sure if it's you guys or maybe the master

**Comment by robbiezhang** [comment]
Is there a node name with testingaciconnector already exist?
> 2018/06/01 19:40:38 Reading ACS credential file "/etc/acs/azure.json"
> 2018/06/01 19:40:38 Load ACS credential file "/etc/acs/azure.json" successfully
> 2018/06/01 19:40:38 Node '**_testingaciconnector_**' with OS type 'Linux' registered
> 2018/06/01 19:40:38 tls: failed to find any PEM data in certificate input

**Comment by rbitia** [comment]
Yeah it was 100% my human error :)

**Comment by rbitia** [comment]
Alright this looks good to me. I'll do a read through of the docs and then merge!

**Comment by sflxn** [comment]
@rbitia VIC is currently a shipping product that's used by customers today.  There are methods to install it that doesn't include building from sources.  The pod vm concept is being implemented in a feature branch of VIC.  When the virtual kubelet provider is no longer an "early release" and we merge the VIC feature branch back into mainline VIC, users will be able to use our existing install methods.  I haven't used help chart much, but it's something that I plan on checking out.  We're planning on adding other deployment models.

**Comment by rbitia** [comment]
Okay yeah basically looking at it from a user that stumbles upon this repo we should figure out what's the easiest way a person can install this provider. If it's from source rn then that's fine but yeah take a look at helm or even just starting a pod with kubectl create -f to create VK.

**Comment by rbitia** [comment]
lgtm! merging

**Pull request merged**
