### PR TITLE
Add Homebrew configuration in .goreleaser.yml

### PR DESCRIPTION
**Pull request by lucperkins**
cc @rbitia

In order to get this to work, someone would need to create a `homebrew-tap` repository under the VK org. That would enable users to install VK like so:

```bash
brew tap virtual-kubelet/tap
brew install virtual-kubelet
```

As far as I know, this would go into effect next time a tag is pushed to `master`.

### CODE REVIEW

**Comment by rbitia** [comment]
@lucperkins hey so I can make a new repo so the path would be virtual-kubelet/homebrew-tap 

That's correct right?

**Comment by lucperkins** [comment]
@rbitia Yep! That is correct

**Comment by pires** [comment]
@cpuguy83 @rbitia if VK is becoming a library, why add a brew?

**Comment by cpuguy83** [comment]
Yeah, let's go ahead and just pass on this one.
Thanks @pires

**Pull request closed without merging**
