### PR TITLE
Use the new  node-cli framework for cmd

### PR DESCRIPTION
**Pull request by cpuguy83**

### CODE REVIEW

**Comment by cpuguy83** [comment]
Seems vendor got out of sync somewhow.

**Comment by cpuguy83** [comment]
Really confused between `go mod tidy` and `go mod vendor`, they seem to be giving different results in `go.mod`

**Comment by hectorj2f** [comment]
Generally, `go mod vendor` should download and store the go modules pruned by `go mod tidy` in a vendor directory.

**Comment by cpuguy83** [comment]
Yes, the issue is it's broken :(

**Pull request closed without merging**
