### PR TITLE
Create a provider to use Azure Batch

### PR DESCRIPTION
**Pull request by lawrencegripper**
This came from a customer engagement I worked on where the customer needed compute with access to GPU's, as the load is very spikey they didn't like the idea of having k8s node count scaling up and down constantly but did like the idea of still using k8s to control jobs. I did a spike on allowing Virtual Kubelet to schedule pods into Azure Batch and this is the result. 

To emulate k8s concept of pods on Batch VMs I created [pod2docker](https://github.com/lawrencegripper/pod2docker) which takes a pod description and creates the necessary bash/docker commands to create the same running environment on Batch. I'm not sure if this makes sense longer term, would welcome thoughts. 

Lots of work to do to cleanup the code and make thinks nicer but wanted to share progress and get feedback.

### CODE REVIEW

**Comment by rbitia** [comment]
Alright we will review in the next day!! thank you! :)

**Comment by lawrencegripper** [comment]
Thanks, I'll try and push a commit shortly to tidy it up a bit more. Lots more cleaning up to do, adding tests and refactoring etc as part of WIP but would be great to get feedback on general approach.

**Comment by rbitia** [comment]
@lawrencegripper you have some conflicting files!

**Comment by lawrencegripper** [comment]
Hi, I got pulled onto some other stuff this week but plan to finish up this work next week - all being well. 

Here is the stuff I plan to tackle, does it sound like a good plan?

Todo:
- [ ] Fix file conflicts
- [ ] Take latest version of pod2docker
- [ ] Add unit tests 
- [ ] Add integration test
- [ ] Add usage docs
- [ ] Add example ARM template which deploys GPU enabled Azure Batch pool for use with this provider
- [ ] Remove auto-creation of Azure Batch pool from provider and require pools already created and configured. Simplifies code and allow for more customization of machines in the pool.

**Comment by lawrencegripper** [comment]
I'm hoping this is pretty much ready to go now. I've included some docs and a Terraform template to deploy everything you need to run GPU tasks from AKS on Azure Batch using low priority nodes. 

The last outstanding bug is around log retrieval. If you try and pull logs before a container is running you will receive an error and once the container runs the log formatting is in `json`... like so:

```json
18:02 $ k logs cuda-vector-add
{"log":"[Vector addition of 50000 elements]\n","stream":"stdout","time":"2018-05-30T17:02:49.967357287Z"}
{"log":"Copy input data from the host memory to the CUDA device\n","stream":"stdout","time":"2018-05-30T17:02:49.967417086Z"}
{"log":"CUDA kernel launch with 196 blocks of 256 threads\n","stream":"stdout","time":"2018-05-30T17:02:49.967423286Z"}
{"log":"Copy output data from the CUDA device to the host memory\n","stream":"stdout","time":"2018-05-30T17:02:49.967427386Z"}
{"log":"Test PASSED\n","stream":"stdout","time":"2018-05-30T17:02:49.967431286Z"}
{"log":"Done\n","stream":"stdout","time":"2018-05-30T17:02:49.967435286Z"}
```

I'll fix those two bugs up tomorrow then I think, with an experimental status, this is no long WIP. Ideally need some more testing to get feedback and contributions as only run in a very limited way so far. 

@alfpark Would you or one of the Batch team be able to try this out?

**Comment by rbitia** [comment]
Super cool! I'll try this out too.

**Comment by lawrencegripper** [comment]
Logs now behaving right too:

logs

**Comment by lawrencegripper** [comment]
Looks like build is failing as I'm using `strings.builder` from [golang 1.10](https://golang.org/doc/go1.10#strings). Would you like me to fallback to golang 1.9 or can I update the build to target 1.10?

**Comment by robbiezhang** [comment]
@lawrencegripper it should be fine to update the build to golang 1.10

**Comment by rbitia** [comment]
Updated the branch - making a test image off it

**Comment by rbitia** [comment]
Executing busybox-1.26.2-r7.trigger
OK: 120 MiB in 33 packages
+ cd /go/src/github.com/virtual-kubelet/virtual-kubelet
+ make build
Building...
# github.com/virtual-kubelet/virtual-kubelet/providers/azurebatch
providers/azurebatch/batch.go:274:15: undefined: strings.Builder
providers/azurebatch/batch_helpers.go:20:31: undefined: strings.Builder
providers/azurebatch/batch_helpers.go:27:25: undefined: strings.Builder
providers/azurebatch/batch_helpers.go:190:8: undefined: strings.Builder
make: *** [Makefile:25: build] Error 2


Doesn't build probably need to run 'dep ensure?'

**Comment by robbiezhang** [comment]
@rbitia you need to upgrade the golang version to 1.10 to build this PR

**Comment by rbitia** [comment]
hmm alright where do I update that? I was looking in the docker file/makefile to change the version

**Comment by lawrencegripper** [comment]
@rbitia can I help? Is this run on your local machine or a test environment?

**Comment by rbitia** [comment]
Hey @lawrencegripper I think we are good to merge :)

**Comment by lawrencegripper** [comment]
Cool, merged in with master, tweaked a few doc issue and added a docker image variable to the terraform template. Gave it another end to end test as well and all worked well!

**Pull request merged**
