### PR TITLE
Modify providers shortcode

### PR DESCRIPTION
**Pull request by lucperkins**
This PR updates the list of providers (see [here](https://virtual-kubelet.netlify.com/docs/providers/#current-providers)) to include a GoDoc link for each provider.

You can see a preview of the new table [here](https://deploy-preview-497--virtual-kubelet.netlify.com/docs/#providers).

### CODE REVIEW

**Comment by lucperkins** [comment]
@cpuguy83 Any suggestions on how to handle that better?

**Comment by lucperkins** [comment]
@cpuguy83 Here's a different potential approach: https://deploy-preview-497--virtual-kubelet.netlify.com/docs/#providers

**Comment by cpuguy83** [comment]
Needs a rebase.

**Comment by lucperkins** [comment]
@cpuguy83 Done

**Pull request merged**
