### PR TITLE
Add basic website

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds a basic website for Virtual Kubelet. This is a *first iteration* but I think it looks decent and contains some basic info and links to click.

You can see what the site looks like here:

https://deploy-preview-437--virtual-kubelet.netlify.com/

### CODE REVIEW

**Comment by lachie83** [comment]
The banner font in "Virtual Kubelet" doesn't show a space betnween "r and t" in my browser. Can you confirm?

**Comment by lucperkins** [comment]
@lachie83 That's actually not the font, that's the logo, and it's by design. You can see the other horizontal logos [here](https://github.com/cncf/artwork/tree/master/virtualkubelet/horizontal).

**Comment by lachie83** [comment]
Okay no worries, thanks for the clarification @lucperkins

**Comment by lucperkins** [comment]
@lachie83 You got it! Thanks for lookin' out 😎

**Comment by rbitia** [comment]
Hey  @lucperkins this looks good. What are your ideas for improving the site? Should we add a developer section and then a provider section? I'm guessing those can be next iterations so we can merge for now :)

**Comment by lucperkins** [comment]
@rbitia Yeah, this is mostly intended to give VK a home on the web. Lots of room for iteration in Q1 and I have some ideas.

**Pull request merged**
